package org.acme

import org.acme.Applicant;


rule "Is approved" ruleflow-group "applicant"

when
    $applicant: Applicant(creditScore > 630)
then
    System.out.println("Applicant " + $applicant.getName() + " is approved");
    modify($applicant) { 
        setApproved(true)
    };
end

rule "Is not approved" ruleflow-group "applicant"

when
    $applicant: Applicant(creditScore < 630)
then
    System.out.println("Applicant " + $applicant.getName() + " is NOT approved");
end